"""Mock execution API for virtual trading center submission tests."""

from __future__ import annotations

from datetime import datetime, timezone
from uuid import uuid4

from pydantic import BaseModel, Field


class ExecutionRequest(BaseModel):
    declaration: dict = Field(..., description="Declaration payload generated by the Strategy/Risk workflow.")


class ExecutionResponse(BaseModel):
    execution_status: str
    trace_id: str
    timestamp: datetime


def submit_declaration(request: ExecutionRequest) -> ExecutionResponse:
    """Simulate successful submission to a virtual trading center."""
    trace_id = str(request.declaration.get("trace_id") or f"mock-exec-{uuid4()}")
    return ExecutionResponse(
        execution_status="submitted",
        trace_id=trace_id,
        timestamp=datetime.now(timezone.utc),
    )
