"""Execution Agent for virtual trading center submission tests."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field

from app.models.trading_state import TradingState


class ExecutionRequest(BaseModel):
    declaration: dict = Field(..., description="Declaration payload generated by the Strategy/Risk workflow.")


class ExecutionResponse(BaseModel):
    execution_status: str
    trace_id: str
    timestamp: datetime


def submit_declaration(request: ExecutionRequest) -> ExecutionResponse:
    """Simulate successful submission to a virtual trading center."""
    trace_id = str(request.declaration.get("trace_id") or f"mock-exec-{uuid4()}")
    return ExecutionResponse(
        execution_status="submitted",
        trace_id=trace_id,
        timestamp=datetime.now(timezone.utc),
    )


def execution_node(state: TradingState | dict[str, Any]) -> dict[str, Any]:
    """Execution Agent node: submit the approved declaration to the mock center."""
    state = _as_state(state)
    _log_node("Execution Agent", state)

    execution = submit_declaration(
        ExecutionRequest(
            declaration={
                "trace_id": state.trace_id,
                "trading_date": state.trading_date,
                "market_type": state.market_type,
                "declaration_curve_mwh": state.declaration_curve_mwh,
                "declaration_ratio": state.declaration_ratio,
                "risk_status": state.risk_status,
            }
        )
    )

    print(
        f"[Execution Agent] trace_id={execution.trace_id} "
        f"execution_status={execution.execution_status} timestamp={execution.timestamp.isoformat()}"
    )
    return {
        "execution_status": execution.execution_status,
        "updated_at": _now(),
    }


def reject_node(state: TradingState | dict[str, Any]) -> dict[str, Any]:
    """Terminal node for invalid declarations that should not be recalculated."""
    state = _as_state(state)
    _log_node("Rejected", state)
    print(f"[Rejected] trace_id={state.trace_id} risk_status={state.risk_status}")
    return {
        "execution_status": "rejected",
        "updated_at": _now(),
    }


def _as_state(state: TradingState | dict[str, Any]) -> TradingState:
    if isinstance(state, TradingState):
        return state
    return TradingState.model_validate(state)


def _log_node(node_name: str, state: TradingState) -> None:
    print(f"[{node_name}] current_node={node_name} trace_id={state.trace_id}")


def _now() -> datetime:
    return datetime.now(timezone.utc)
